package com.mmt.controller;
import com.mmt.model.*; import com.mmt.repository.*; import com.mmt.service.*; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/auth") @CrossOrigin(origins="*")
public class AuthController {
 private final UserRepository repo; private final UtilService util; private final OtpCodeRepository otps; private final EmailService mail;
 public AuthController(UserRepository r,UtilService u,OtpCodeRepository o,EmailService m){repo=r;util=u;otps=o;mail=m;}
 private String otp(){return String.format("%06d",new Random().nextInt(1_000_000));}
 private Map<String,Object> issue(String email,String purpose){String code=otp(); otps.save(OtpCode.builder().email(email).purpose(purpose).code(code).expiresAt(LocalDateTime.now().plusMinutes(10)).used(false).build()); mail.sendOtp(email,purpose,code); Map<String,Object> out=new HashMap<>(); out.put("message","OTP sent to your email"); out.put("emailConfigured",mail.configured()); if(!mail.configured()) out.put("devOtp",code); return out;}
 private void verifyOtp(String email,String purpose,String code){OtpCode o=otps.findTopByEmailIgnoreCaseAndPurposeAndUsedFalseOrderByIdDesc(email,purpose).orElseThrow(()->new RuntimeException("OTP not found. Request a new OTP.")); if(o.getExpiresAt().isBefore(LocalDateTime.now())) throw new RuntimeException("OTP expired"); if(!o.getCode().equals(code)) throw new RuntimeException("Invalid OTP"); o.setUsed(true); otps.save(o);}
 @PostMapping("/signup/request-otp") public Map<String,Object> signupOtp(@RequestBody Map<String,String>b){String e=b.get("email"); if(e==null||e.isBlank())throw new RuntimeException("Email is required"); if(repo.findAll().stream().anyMatch(u->u.getEmail().equalsIgnoreCase(e)))throw new RuntimeException("Email already registered"); return issue(e,"SIGNUP");}
 @PostMapping("/signup/verify") public User signupVerify(@RequestBody Map<String,String>b){String e=b.get("email"); verifyOtp(e,"SIGNUP",b.get("otp")); if(repo.findAll().stream().anyMatch(u->u.getEmail().equalsIgnoreCase(e)))throw new RuntimeException("Email already registered"); return repo.save(User.builder().email(e).name(b.get("name")).passwordHash(util.hash(b.get("password"))).preferences(b.getOrDefault("preferences","beach,luxury,mountains")).favoriteDestination(b.getOrDefault("favoriteDestination","Goa")).createdAt(LocalDateTime.now()).build());}
 @PostMapping("/login/request-otp") public Map<String,Object> loginOtp(@RequestBody Map<String,String>b){User u=find(b.get("email")); if(!u.getPasswordHash().equals(util.hash(b.get("password"))))throw new RuntimeException("Invalid email or password"); return issue(u.getEmail(),"LOGIN");}
 @PostMapping("/login/verify") public User loginVerify(@RequestBody Map<String,String>b){verifyOtp(b.get("email"),"LOGIN",b.get("otp")); return find(b.get("email"));}
 @PostMapping("/forgot/request-otp") public Map<String,Object> forgotOtp(@RequestBody Map<String,String>b){find(b.get("email")); return issue(b.get("email"),"PASSWORD RESET");}
 @PostMapping("/forgot/reset") public Map<String,Object> reset(@RequestBody Map<String,String>b){verifyOtp(b.get("email"),"PASSWORD RESET",b.get("otp")); User u=find(b.get("email")); u.setPasswordHash(util.hash(b.get("newPassword"))); repo.save(u); return Map.of("message","Password reset successfully");}
 @PostMapping("/signup") public User signup(@RequestBody Map<String,String>b){return repo.save(User.builder().email(b.get("email")).name(b.get("name")).passwordHash(util.hash(b.get("password"))).preferences(b.getOrDefault("preferences","beach,city,food")).favoriteDestination(b.getOrDefault("favoriteDestination","Goa")).createdAt(LocalDateTime.now()).build());}
 @PostMapping("/login") public User login(@RequestBody Map<String,String>b){User u=find(b.get("email")); if(!u.getPasswordHash().equals(util.hash(b.get("password"))))throw new RuntimeException("Invalid email or password"); return u;}
 private User find(String email){return repo.findAll().stream().filter(x->x.getEmail().equalsIgnoreCase(email)).findFirst().orElseThrow(()->new RuntimeException("User not found"));}
}
