package com.mmt.service;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.*; import com.mmt.model.LocationRecord; import com.mmt.repository.LocationRepository; import org.springframework.boot.CommandLineRunner; import org.springframework.stereotype.Service; import org.springframework.web.client.RestClient; import java.util.*;
@Service public class LocationSyncService implements CommandLineRunner {
 private final LocationRepository repo; private final ObjectMapper mapper=new ObjectMapper(); private final RestClient client=RestClient.create();
 public LocationSyncService(LocationRepository r){repo=r;}
 public void run(String...args){ if(repo.countByType("DISTRICT")==0) syncDistricts(); if(repo.countByType("AIRPORT")==0) syncAirports(); seedFallback(); }
 private void syncDistricts(){try{String json=client.get().uri("https://raw.githubusercontent.com/KTBsomen/Indian-state-district-json/main/india-states-districts-latest.json").retrieve().body(String.class); List<Map<String,Object>> states=mapper.readValue(json,new TypeReference<>(){}); for(Map<String,Object>s:states){String state=String.valueOf(s.get("state")); repo.save(LocationRecord.builder().type("STATE").name(state).state(state).country("India").build()); for(Object d:(List<?>)s.get("districts")){String district=String.valueOf(d); repo.save(LocationRecord.builder().type("DISTRICT").name(district).state(state).district(district).city(district).country("India").build());}}}catch(Exception ignored){} }
 private void syncAirports(){try{String json=client.get().uri("https://raw.githubusercontent.com/mwgg/Airports/master/airports.json").retrieve().body(String.class); Map<String,Map<String,Object>> all=mapper.readValue(json,new TypeReference<>(){}); for(Map<String,Object>a:all.values()){if(!"IN".equalsIgnoreCase(String.valueOf(a.get("country"))))continue; String iata=String.valueOf(a.getOrDefault("iata","")); if(iata.isBlank()||"null".equals(iata))continue; repo.save(LocationRecord.builder().type("AIRPORT").name(String.valueOf(a.get("name"))).city(String.valueOf(a.get("city"))).state(String.valueOf(a.getOrDefault("state",""))).code(iata).country("India").latitude(toD(a.get("lat"))).longitude(toD(a.get("lon"))).build());}}catch(Exception ignored){} }
 private Double toD(Object o){try{return Double.valueOf(String.valueOf(o));}catch(Exception e){return null;}}
 private void seedFallback(){if(repo.countByType("STATE")==0){for(String s:new String[]{"Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Delhi","Jammu and Kashmir","Ladakh","Puducherry","Chandigarh","Andaman and Nicobar Islands","Dadra and Nagar Haveli and Daman and Diu","Lakshadweep"})repo.save(LocationRecord.builder().type("STATE").name(s).state(s).country("India").build());}}
}
