package com.mmt.service;
import com.fasterxml.jackson.databind.ObjectMapper; import com.mmt.config.WebSocketConfig; import com.mmt.model.*; import com.mmt.repository.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value; import org.springframework.web.socket.TextMessage; import org.springframework.web.socket.WebSocketSession; import java.time.*; import java.util.*;
@Service public class RealTimeEngine { private final FlightRepository flights; private final HotelRepository hotels; private final PriceHistoryRepository history; private final FlightStatusUpdateRepository updates; private final HotelRoomRepository rooms; private final UtilService util; private final ObjectMapper mapper=new ObjectMapper().findAndRegisterModules(); private int tick=0;
 @Value("${aviation.api.key:}") private String aviationApiKey;
 public RealTimeEngine(FlightRepository f,HotelRepository h,PriceHistoryRepository ph,FlightStatusUpdateRepository u,HotelRoomRepository r,UtilService x){flights=f;hotels=h;history=ph;updates=u;rooms=r;util=x;}
 @Scheduled(fixedRate=15000) public void tick(){tick++; List<Map<String,Object>> events=new ArrayList<>(); for(Flight f:flights.findAll()){if(f.getStatus()==null)f.setStatus("ON TIME"); int demand=Math.max(20,Math.min(95,(f.getTotalSeats()-f.getAvailableSeats())*100/Math.max(1,f.getTotalSeats()))); if(tick%2==0 && f.getAvailableSeats()>0)f.setAvailableSeats(Math.max(0,f.getAvailableSeats()-1));
 // When a real Aviationstack key is configured, LiveFlightApiService owns the external flight status.
 // This engine continues live demand/price telemetry without overwriting the provider status.
 if(aviationApiKey==null || aviationApiKey.isBlank()){ if(tick%4==0){f.setStatus("DELAYED");f.setDelayMinutes(60);f.setDelayReason("Air traffic / weather conditions");} else if(tick%3==0)f.setStatus("BOARDING"); else if(tick%5==0)f.setStatus("DEPARTED"); else f.setStatus("ON TIME"); }
 int delay=f.getDelayMinutes()==null?0:f.getDelayMinutes(); f.setEstimatedDepartureTime(f.getDepartureTime().plusMinutes(delay)); f.setEstimatedArrivalTime(f.getArrivalTime().plusMinutes(delay)); f.setLastUpdated(LocalDateTime.now()); double base=f.getBasePrice()==null?f.getPrice():f.getBasePrice(); double mult=util.multiplier(demand); f.setPrice(Math.round(base*mult*100.0)/100.0); flights.save(f); history.save(PriceHistory.builder().itemType("FLIGHT").itemId(f.getId()).price(f.getPrice()).multiplier(mult).reason(util.pricingReason(demand)).recordedAt(LocalDateTime.now()).build()); updates.save(FlightStatusUpdate.builder().flightId(f.getId()).status(f.getStatus()).delayMinutes(delay).message(f.getStatus().equals("DELAYED")?"Delayed by 1h — reason: "+f.getDelayReason():f.getStatus()).estimatedArrivalTime(f.getEstimatedArrivalTime()).updatedAt(LocalDateTime.now()).build()); events.add(Map.of("type","FLIGHT_UPDATE","flight",f,"notification", "DELAYED".equals(f.getStatus())?"Flight "+f.getFlightNumber()+" delayed by 1h due to "+f.getDelayReason():"Flight "+f.getFlightNumber()+" is "+f.getStatus())); }
 for(Hotel h:hotels.findAll()){int d=h.getDemandScore()==null?60:h.getDemandScore(); double mult=util.multiplier(d); h.setCurrentPrice(Math.round(h.getBasePrice()*mult*100.0)/100.0); hotels.save(h); for(HotelRoom r:rooms.findByHotelId(h.getId())){ if(tick%3==0 && r.getAvailableRooms()>0) r.setAvailableRooms(r.getAvailableRooms()-1); else if(tick%5==0 && r.getAvailableRooms()<r.getTotalRooms()) r.setAvailableRooms(r.getAvailableRooms()+1); rooms.save(r); } history.save(PriceHistory.builder().itemType("HOTEL").itemId(h.getId()).price(h.getCurrentPrice()).multiplier(mult).reason(util.pricingReason(d)).recordedAt(LocalDateTime.now()).build()); events.add(Map.of("type","HOTEL_UPDATE","hotel",h));}
 broadcast(events); }
 private void broadcast(Object payload){try{String json=mapper.writeValueAsString(payload); for(WebSocketSession s:WebSocketConfig.SESSIONS){if(s.isOpen())s.sendMessage(new TextMessage(json));}}catch(Exception ignored){}}
}
